################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3000

################################################################################
##                               Database options                             ##
################################################################################
database:
  host: "${DATABASE_HOST}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  database: "${DATABASE_NAME}"
  scheme: "${DATABASE_SCHEME}"
  port: "${DATABASE_PORT}"
  connectionTimeoutMillis: 2000
  max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: http

node:
  interval: 600
  max_txs: 256
  send_interval: 30
  ipfs_api_url: https://api-ipfs.bosagora.info
  ipfs_gateway_url: https://ipfs.bosagora.info
  ipfs_test: false

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      expression: "*/1 * * * * *"
    - name: send_block
      enable: true
      expression: "*/14 * * * * *"

contracts:
  publisherKey: "${PUBLISHER_KEY}"
  purchaseAddress: "${STORE_PURCHASE_CONTRACT_ADDRESS}"

setting:
  accessKey:
    - key: "${ACCESS_KEY0}"
      sender: "${SENDER0}"
      waiting: "${WAITING0}"
    - key: "${ACCESS_KEY1}"
      sender: "${SENDER1}"
      waiting: "${WAITING1}"
  relayEndpoint: "${RELAY_ENDPOINT}"
  relayAccessKey: "${RELAY_ACCESS_KEY}"
  smsEndpoint: "${SMS_ENDPOINT}"
  smsAccessKey: "${SMS_ACCESS_KEY}"
