################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "${HOST_IP}"
    # Port on which we bind (default: 3000)
    port: "${HOST_PORT}"

################################################################################
##                               Database options                             ##
################################################################################
database:
  host: "${DATABASE_HOST}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  database: "${DATABASE_NAME}"
  scheme: "${DATABASE_SCHEME}"
  port: "${DATABASE_PORT}"
  connectionTimeoutMillis: 2000
  max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
  # Values: error, warn, info, http, verbose, debug, silly
  level: "${LOGGING_LEVEL}"

node:
  interval: ${NODE_INTERVAL}
  max_txs: ${NODE_MAX_TXS}
  send_interval: ${NODE_SEND_INTERVAL}
  storage_type: "${NODE_STORAGE_TYPE}"
  ipfs_api_url: "${NODE_IPFS_API_URL}"
  ipfs_gateway_url: "${NODE_IPFS_GATEWAY_URL}"
  ipfs_test: ${NODE_IPFS_TEST}
  s3_region: "${NODE_S3_REGION}"
  s3_access_key: "${NODE_S3_ACCESS_KEY}"
  s3_secret_key: "${NODE_S3_SECRET_KEY}"
  s3_bucket: "${NODE_S3_BUCKET}"

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      expression: "*/1 * * * * *"
    - name: send_block
      enable: true
      expression: "*/14 * * * * *"

contracts:
  publisherKey: "${PUBLISHER_KEY}"
  purchaseAddress: "${STORE_PURCHASE_CONTRACT_ADDRESS}"

setting:
  accessKey:
    - key: "${ACCESS_KEY0}"
      sender: "${SENDER0}"
      waiting: "${WAITING0}"
    - key: "${ACCESS_KEY1}"
      sender: "${SENDER1}"
      waiting: "${WAITING1}"
  purchaseSigners:
    - sender: "${SENDER0}"
      collectors:
        - "${COLLECTOR0}"
      delegate: "${DELEGATE_KEY0}"
    - sender: "${SENDER1}"
      collectors:
        - "${COLLECTOR1}"
      delegate: "${DELEGATE_KEY1}"
  relayEndpoint: "${RELAY_ENDPOINT}"
  relayAccessKey: "${RELAY_ACCESS_KEY}"
  smsEndpoint: "${SMS_ENDPOINT}"
  smsAccessKey: "${SMS_ACCESS_KEY}"
  messageEnable: "${MESSAGE_ENABLE}"
  timezone: "Asia/Seoul"
  allowedShopIdPrefix: "0x0001"
