################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "${HOST_IP}"
    # Port on which we bind (default: 3000)
    port: "${HOST_PORT}"

################################################################################
##                               Logging options                              ##
################################################################################
logging:
  # Values: error, warn, info, http, verbose, debug, silly
  level: "${LOGGING_LEVEL}"

database:
  path: "${DATABASE_PATH}"

node:
  interval: ${NODE_INTERVAL}
  max_txs: ${NODE_MAX_TXS}
  send_interval: ${NODE_SEND_INTERVAL}
  ipfs_api_url: "${NODE_IPFS_API_URL}"
  ipfs_gateway_url: "${NODE_IPFS_GATEWAY_URL}"
  ipfs_test: ${NODE_IPFS_TEST}

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      expression: "*/1 * * * * *"
    - name: send_block
      enable: true
      expression: "*/14 * * * * *"

contracts:
  publisherKey: "${PUBLISHER_KEY}"
  purchaseAddress: "${STORE_PURCHASE_CONTRACT_ADDRESS}"

setting:
  accessKey: "${ACCESS_KEY}"
  relayEndpoint: "${RELAY_ENDPOINT}"
  relayAccessKey: "${RELAY_ACCESS_KEY}"
  smsEndpoint: "${SMS_ENDPOINT}"
  smsAccessKey: "${SMS_ACCESS_KEY}"
  smsSender: "${SMS_SENDER}"
  tokenSymbol: "${TOKEN_SYMBOL}"
  messageEnable: "${MESSAGE_ENABLE}"
